version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: mrp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mrp_db
    ports:
      - "5432:5432"  # Use port 5433 on host to avoid conflicts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mrp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: